# Generated by Django 3.1.5 on 2021-01-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshorten', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlshortener',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
